- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    - name: Create vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout
    - name: Create Public Subnet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out
    - name: Create Public Subnet 2 in Zone 2
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub2Cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out
    - name: Create Public Subnet 3 in Zone 3
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub3Cidr }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        map_public : yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out
    - name: create Private Subnet 1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{state}}"
        cidr: "{{ PrivSub1Cidr }}"
        resource_tags:
          Name: vprofile_privsub1
      register: privsub1_out

    - name: create Private subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{state}}"
        cidr: "{{ PrivSub2Cidr }}"
        resource_tags:
          Name: vprofile_privsub2
      register: privsub2_out



    - name: create Private subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{state}}"
        cidr: "{{ PrivSub3Cidr }}"
        resource_tags:
          Name: vprofile_privsub3
      register: privsub3_out
